const mascotas = [
   {
    tipoMascota:'Gatos',
    razas: [    
      {	
         raza:	'Gato europeo',
         origen: 	'Egipto',
         alturaCm:	'30',
         pesoKg:	'5',
         pelo:	'corto',
         colores:	'variados',
         caracter:	'tranquilo',
         esperanzaVida:	'15 años',
       } ,	
       {	
         raza:	'Gato azul ruso',
         origen: 	'Askhangelsk, Rusia',
         alturaCm:	'30',
         pesoKg:	'3',
         pelo:	'corto',
         colores:	'gris azulado',
         caracter:	'cariñoso',
         esperanzaVida:	'20 años',
       } ,	
       {	
         raza:	'Siberiano',
         origen: 	'Siberia',
         alturaCm:	'35',
         pesoKg:	'6',
         pelo:	'largo',
         colores:	'variados',
         caracter:	'juguetón',
         esperanzaVida:	'20 años',
       } ,	
       {	
         raza:	'Bombay',
         origen: 	'USA',
         alturaCm:	'30',
         pesoKg:	'4',
         pelo:	'corto',
         colores:	'negro',
         caracter:	'cariñoso',
         esperanzaVida:	'15 años',
       } ,	
       {	
         raza:	'Ragdoll',
         origen: 	'USA',
         alturaCm:	'35',
         pesoKg:	'6',
         pelo:	'largo',
         colores:	'variados',
         caracter:	'dócil',
         esperanzaVida:	'15 años',
       } ,
      ]
   },
   {      
   tipoMascota: 'Perros',
   razas: [
      {	
         raza:	'Labrador ',
         origen: 	'Reino Unido',
         alturaCm:	'56',
         pesoKg:	'35',
         pelo:	'corto',
         colores:	'variados',
         caracter:	'cariñoso',
         esperanzaVida:	'15 años',
       } ,	
       {	
         raza:	'Beagle',
         origen: 	'Gran Bretaña',
         alturaCm:	'37',
         pesoKg:	'15',
         pelo:	'corto',
         colores:	'tricolor',
         caracter:	'juguetón',
         esperanzaVida:	'15 años',
       } ,	
       {	
         raza:	'Border Collie',
         origen: 	'Escocia',
         alturaCm:	'52',
         pesoKg:	'6',
         pelo:	'largo',
         colores:	'blanco y negro / blanco y marrón',
         caracter:	'inteligente',
         esperanzaVida:	'15 años',
       } ,	
       {	
         raza:	'Lebrel Italiano',
         origen: 	'Italia',
         alturaCm:	'35',
         pesoKg:	'4',
         pelo:	'corto',
         colores:	'negro / gris / arena',
         caracter:	'cariñoso',
         esperanzaVida:	'15 años',
       } ,	
       {	
         raza:	'Bichón maltés',
         origen: 	'Italia',
         alturaCm:	'23',
         pesoKg:	'3,5',
         pelo:	'largo',
         colores:	'blanco',
         caracter:	'tranquilo',
         esperanzaVida:	'15 años',
       } ,	                            
      ]
   },
]
